#############################################################################
# Makefile for building: Simulacao
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Sep 23 22:39:03 2012
# Project:  Simulacao.pro
# Template: app
# Command: /opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec /opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Simulacao.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -I. -I/opt/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I/opt/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I/opt/QtSDK/Desktop/Qt/4.8.1/gcc/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LIBS          = $(SUBLIBS)  -L/opt/QtSDK/Desktop/Qt/4.8.1/gcc/lib -lQtGui -L/opt/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = atendente.cpp \
		carro.cpp \
		gerador.cpp \
		lavacao.cpp \
		main.cpp \
		porta.cpp \
		dispose.cpp \
		mainwindow.cpp \
		configuracaoinicialdialog.cpp moc_atendente.cpp \
		moc_carro.cpp \
		moc_lavacao.cpp \
		moc_porta.cpp \
		moc_dispose.cpp \
		moc_mainwindow.cpp \
		moc_configuracaoinicialdialog.cpp
OBJECTS       = atendente.o \
		carro.o \
		gerador.o \
		lavacao.o \
		main.o \
		porta.o \
		dispose.o \
		mainwindow.o \
		configuracaoinicialdialog.o \
		moc_atendente.o \
		moc_carro.o \
		moc_lavacao.o \
		moc_porta.o \
		moc_dispose.o \
		moc_mainwindow.o \
		moc_configuracaoinicialdialog.o
DIST          = /opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		Simulacao.pro
QMAKE_TARGET  = Simulacao
DESTDIR       = 
TARGET        = Simulacao

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_configuracaoinicialdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: Simulacao.pro  /opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++/qmake.conf /opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl \
		/opt/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl
	$(QMAKE) -spec /opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Simulacao.pro
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl:
/opt/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Simulacao.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Simulacao1.0.0 || $(MKDIR) .tmp/Simulacao1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Simulacao1.0.0/ && $(COPY_FILE) --parents atendente.h carro.h config.h gerador.h lavacao.h porta.h dispose.h mainwindow.h configuracaoinicialdialog.h .tmp/Simulacao1.0.0/ && $(COPY_FILE) --parents atendente.cpp carro.cpp gerador.cpp lavacao.cpp main.cpp porta.cpp dispose.cpp mainwindow.cpp configuracaoinicialdialog.cpp .tmp/Simulacao1.0.0/ && $(COPY_FILE) --parents mainwindow.ui configuracaoinicialdialog.ui .tmp/Simulacao1.0.0/ && (cd `dirname .tmp/Simulacao1.0.0` && $(TAR) Simulacao1.0.0.tar Simulacao1.0.0 && $(COMPRESS) Simulacao1.0.0.tar) && $(MOVE) `dirname .tmp/Simulacao1.0.0`/Simulacao1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Simulacao1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_atendente.cpp moc_carro.cpp moc_lavacao.cpp moc_porta.cpp moc_dispose.cpp moc_mainwindow.cpp moc_configuracaoinicialdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_atendente.cpp moc_carro.cpp moc_lavacao.cpp moc_porta.cpp moc_dispose.cpp moc_mainwindow.cpp moc_configuracaoinicialdialog.cpp
moc_atendente.cpp: carro.h \
		gerador.h \
		config.h \
		atendente.h
	/opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) atendente.h -o moc_atendente.cpp

moc_carro.cpp: carro.h
	/opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) carro.h -o moc_carro.cpp

moc_lavacao.cpp: carro.h \
		porta.h \
		config.h \
		gerador.h \
		atendente.h \
		dispose.h \
		lavacao.h
	/opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) lavacao.h -o moc_lavacao.cpp

moc_porta.cpp: carro.h \
		config.h \
		gerador.h \
		porta.h
	/opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) porta.h -o moc_porta.cpp

moc_dispose.cpp: carro.h \
		dispose.h
	/opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) dispose.h -o moc_dispose.cpp

moc_mainwindow.cpp: lavacao.h \
		carro.h \
		porta.h \
		config.h \
		gerador.h \
		atendente.h \
		dispose.h \
		mainwindow.h
	/opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_configuracaoinicialdialog.cpp: config.h \
		configuracaoinicialdialog.h
	/opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) configuracaoinicialdialog.h -o moc_configuracaoinicialdialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_configuracaoinicialdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_configuracaoinicialdialog.h
ui_mainwindow.h: mainwindow.ui
	/opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_configuracaoinicialdialog.h: configuracaoinicialdialog.ui
	/opt/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic configuracaoinicialdialog.ui -o ui_configuracaoinicialdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

atendente.o: atendente.cpp atendente.h \
		carro.h \
		gerador.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o atendente.o atendente.cpp

carro.o: carro.cpp carro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o carro.o carro.cpp

gerador.o: gerador.cpp gerador.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gerador.o gerador.cpp

lavacao.o: lavacao.cpp lavacao.h \
		carro.h \
		porta.h \
		config.h \
		gerador.h \
		atendente.h \
		dispose.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lavacao.o lavacao.cpp

main.o: main.cpp mainwindow.h \
		lavacao.h \
		carro.h \
		porta.h \
		config.h \
		gerador.h \
		atendente.h \
		dispose.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

porta.o: porta.cpp porta.h \
		carro.h \
		config.h \
		gerador.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o porta.o porta.cpp

dispose.o: dispose.cpp dispose.h \
		carro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dispose.o dispose.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		lavacao.h \
		carro.h \
		porta.h \
		config.h \
		gerador.h \
		atendente.h \
		dispose.h \
		ui_mainwindow.h \
		configuracaoinicialdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

configuracaoinicialdialog.o: configuracaoinicialdialog.cpp configuracaoinicialdialog.h \
		config.h \
		ui_configuracaoinicialdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configuracaoinicialdialog.o configuracaoinicialdialog.cpp

moc_atendente.o: moc_atendente.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_atendente.o moc_atendente.cpp

moc_carro.o: moc_carro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_carro.o moc_carro.cpp

moc_lavacao.o: moc_lavacao.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lavacao.o moc_lavacao.cpp

moc_porta.o: moc_porta.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_porta.o moc_porta.cpp

moc_dispose.o: moc_dispose.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dispose.o moc_dispose.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_configuracaoinicialdialog.o: moc_configuracaoinicialdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configuracaoinicialdialog.o moc_configuracaoinicialdialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

